# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d1f5f203461c63dc7ba741d7d7b0dae433e448cb69e227115e68bb26d08cbbd21ee1eca9e9e80b674eeb3be083b7788faff96e650812666dea0d2dd06c55f8

test:
  secret_key_base: ebc8d5ce3aaff659a21a1c151cf574b574d282b9df07dcca44d7f16825dd821f14483d3fdbf8d902ca01068f369a3bd21af15853910a26dbd0d772df56a20bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
